# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('is_complete', models.BooleanField(default=True)),
            ],
        ),
    ]
