# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
